### PR TITLE
Query for the specific type being checked. Fixes #27

### LINKED ISSUE #27: resolver.query should query specific type (if specified)
Currently `has_dns` always queries with [Dnsruby::Types::ANY](https://github.com/spotify/rspec-dns/blob/master/lib/rspec-dns/have_dns.rb#L156). This doesn't always produce the desired result.

```ruby
resolver.query(@_name, Dnsruby::Types.ANY)
```

This doesn't always produce the desired answer. Suggest changing this to:

```ruby
resolver.query(@_name, _options[:type] || Dnsruby::Types.ANY)
```

Which will query with the specifically request type (e.g. using `with_type('A')`) and return the expected answer.

**TL;DR**

I am using rspec-dns to check my DNS settings (primary DNS with some subdomains delegated to AWS Route53).

I would like to spec that resolving `route53.kerkdienstgemist.nl` with type 'A' is expected to return a specific IP-address.

With delegated responsibility for this subdomain, resolving with `ANY` will only return the nameservers (of Route53):

```bash
$ dig -t any route53.kerkdienstgemist.nl
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.8.3-P1 <<>> -t any route53.kerkdienstgemist.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55572
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 4

;; QUESTION SECTION:
;route53.kerkdienstgemist.nl.	IN	ANY

;; ANSWER SECTION:
route53.kerkdienstgemist.nl. 60	IN	NS	ns-1517.awsdns-61.org.
route53.kerkdienstgemist.nl. 60	IN	NS	ns-279.awsdns-34.com.
route53.kerkdienstgemist.nl. 60	IN	NS	ns-544.awsdns-04.net.
route53.kerkdienstgemist.nl. 60	IN	NS	ns-1684.awsdns-18.co.uk.

;; ADDITIONAL SECTION:
ns-544.awsdns-04.net.	33717	IN	A	205.251.194.32
ns-1684.awsdns-18.co.uk. 36384	IN	A	205.251.198.148
ns-1517.awsdns-61.org.	32405	IN	A	205.251.197.237
ns-279.awsdns-34.com.	34224	IN	A	205.251.193.23

;; Query time: 22 msec
;; SERVER: 192.168.2.254#53(192.168.2.254)
;; WHEN: Fri Oct 21 21:32:19 2016
;; MSG SIZE  rcvd: 249
```

Resolving with one of the specified nameservers, I get:

```bash
$ dig @ns-1188.awsdns-20.org -t any video.kerkdienstgemist.nl

; <<>> DiG 9.8.3-P1 <<>> @ns-1188.awsdns-20.org -t any video.kerkdienstgemist.nl
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53218
;; flags: qr aa rd; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;video.kerkdienstgemist.nl.	IN	ANY

;; ANSWER SECTION:
video.kerkdienstgemist.nl. 60	IN	A	54.247.171.136
video.kerkdienstgemist.nl. 172800 IN	NS	ns-1188.awsdns-20.org.
video.kerkdienstgemist.nl. 172800 IN	NS	ns-1971.awsdns-54.co.uk.
video.kerkdienstgemist.nl. 172800 IN	NS	ns-267.awsdns-33.com.
video.kerkdienstgemist.nl. 172800 IN	NS	ns-546.awsdns-04.net.
video.kerkdienstgemist.nl. 900	IN	SOA	ns-1971.awsdns-54.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 18 msec
;; SERVER: 205.251.196.164#53(205.251.196.164)
;; WHEN: Fri Oct 21 21:40:49 2016
;; MSG SIZE  rcvd: 260
```

Which contains the 'A' record I'm after.

When I resolve with type 'A' I do get an answer with the IP-address I'm after:

```bash
$ dig -t a route53.kerkdienstgemist.nl

; <<>> DiG 9.8.3-P1 <<>> -t a route53.kerkdienstgemist.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50744
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;route53.kerkdienstgemist.nl.	IN	A

;; ANSWER SECTION:
route53.kerkdienstgemist.nl. 60	IN	A	54.74.125.3

;; Query time: 18 msec
;; SERVER: 192.168.2.254#53(192.168.2.254)
;; WHEN: Fri Oct 21 21:45:36 2016
;; MSG SIZE  rcvd: 61
```

Testing this kind of specific type query is currently not possible with rspec-dns. I will post a PR with a fix.

### PR DESCRIPTION
**Pull request by kjwierenga**

### CODE REVIEW

**Comment by otahi** [comment]
@kjwierenga Thank you for your pull request!
I understand that you are going to fix the issue #27.

I think that queries with type 'ANY' happen some troubles. So, I think it had better to be specified with type. But we need to care the following test case.

```ruby
require 'spec_helper'

describe 'www.example.com' do
  it { is_expected.to have_dns.with_type('A').and_ttl(300).and_address('192.0.2.4') }
  it { is_expected.to have_dns.with_type('TXT').and_ttl(300).and_data('a=b') }
end
```

In this case, we need share 1 query for 2 judges. So, we need to care this situations. I think it had better to add an option to specify query type. What do you think?

**Comment by kjwierenga** [comment]
@otahi Yes, this is a fix for #27

The case you're describing Just Works™ because every `have_dns` call sets up a new context. Afaik there is no sharing of the query.

**Comment by kjwierenga** [comment]
Pushed spec with adapted examples from README.md. No stubbing to show that this PR doesn't break things. Don't merge this commit (b22e55e6b91bf0f3ff98c85dc7889b362803d362) as it is brittle (subject to DNS changes for example.com) and does actual DNS requests.

**Comment by otahi** [comment]
@kjwierenga Thank you for your experiment. I misunderstood the independency of queries for a long time... I tested with your spec (b22e55e) and this PR is LGTM.

What do you think, @vzctl ? If you are OK, I will merge this PR(except b22e55e).

**Comment by vzctl** [comment]
:+1:

**Comment by vzctl** [comment]
By the way, I trust your decisions, Hiroshi. You don't have to ask me, and definitely do not block on me.

**Comment by kjwierenga** [comment]
Excellent, thanks.

**Comment by otahi** [comment]
@kjwierenga So, please remove the commit b22e55e. I have stored this commit to the [Gist](https://gist.github.com/otahi/e98d69731f5d55bf130d540289babcfe).

Then I will merge this PR soon.

**Comment by kjwierenga** [comment]
@otahi done. thanks for support

**Comment by otahi** [comment]
@kjwierenga I have merged! Thank you for your valuable pull request!

**Comment by otahi** [comment]
@vzctl Oh, I remember I don't have ownership of rspec-dns gem yet. Please [add me to the owner members](http://stackoverflow.com/questions/8487218/how-to-add-more-owners-to-a-gem-in-rubygem) or release 0.1.7.

**Comment by vzctl** [comment]
@otahi you can release it by tagging, it's automated using travis.

**Comment by otahi** [comment]
Thank you for all.

I have released [v0.1.7](https://rubygems.org/gems/rspec-dns/versions/0.1.7). https://github.com/spotify/rspec-dns/releases/tag/v0.1.7

**Pull request merged**
